# name: 'Matugen'
# preferred_background: {{ colors.surface_container_lowest.dark.hex_stripped }}

[dark]
# preferred_background: {{ colors.surface_container_lowest.dark.hex_stripped }}

# Syntax highlighting
fish_color_normal {{ colors.on_surface.dark.hex_stripped }}
fish_color_command {{ colors.primary.dark.hex_stripped }}
fish_color_keyword {{ colors.tertiary.dark.hex_stripped }}
fish_color_quote {{ colors.tertiary.dark.hex_stripped }}
fish_color_redirection {{ colors.primary.dark.hex_stripped }}
fish_color_end {{ colors.on_surface_variant.dark.hex_stripped }}
fish_color_error {{ colors.error.dark.hex_stripped }}
fish_color_param {{ colors.on_surface_variant.dark.hex_stripped }}
fish_color_comment {{ colors.outline.dark.hex_stripped }}
fish_color_operator {{ colors.tertiary.dark.hex_stripped }}
fish_color_escape {{ colors.tertiary.dark.hex_stripped }}
fish_color_autosuggestion {{ colors.outline.dark.hex_stripped }}
fish_color_valid_path {{ colors.secondary.dark.hex_stripped }} --underline
fish_color_option {{ colors.tertiary.dark.hex_stripped }}
fish_color_status {{ colors.error.dark.hex_stripped }}
fish_color_history_current {{ colors.secondary.dark.hex_stripped }}

# Prompt colors
fish_color_cwd {{ colors.primary.dark.hex_stripped }}
fish_color_cwd_root {{ colors.error.dark.hex_stripped }}
fish_color_user {{ colors.secondary.dark.hex_stripped }}
fish_color_host {{ colors.tertiary.dark.hex_stripped }}
fish_color_host_remote {{ colors.tertiary.dark.hex_stripped }}
fish_color_cancel {{ colors.error.dark.hex_stripped }}

# Selection and search
fish_color_selection --background={{ colors.surface_container_highest.dark.hex_stripped }}
fish_color_search_match --background={{ colors.surface_container.dark.hex_stripped }}

# Pager colors
fish_pager_color_progress {{ colors.tertiary.dark.hex_stripped }}
fish_pager_color_background
fish_pager_color_prefix {{ colors.primary.dark.hex_stripped }}
fish_pager_color_completion {{ colors.on_surface.dark.hex_stripped }}
fish_pager_color_description {{ colors.outline.dark.hex_stripped }}
fish_pager_color_selected_background --background={{ colors.surface_container_highest.dark.hex_stripped }}
fish_pager_color_selected_prefix {{ colors.primary.dark.hex_stripped }}
fish_pager_color_selected_completion {{ colors.on_surface.dark.hex_stripped }}
fish_pager_color_selected_description {{ colors.outline.dark.hex_stripped }}
fish_pager_color_secondary_background --background={{ colors.surface_container.dark.hex_stripped }}
fish_pager_color_secondary_prefix {{ colors.primary.dark.hex_stripped }}
fish_pager_color_secondary_completion {{ colors.on_surface.dark.hex_stripped }}
fish_pager_color_secondary_description {{ colors.outline.dark.hex_stripped }}
